serverKey=SERVER.BatchSvr
log4j.file=./config/log4j.ini
log4j.thread=1
log4j.writeTime=true
log4j.async=true
symbolCategory=SOL|JLP|USDE|SUSDE|SONIC
dbpool.cfg=./config/DBPoolConfig.ini
dbpool.default=MYSQL0


Schedule.Config=./config/quartz.properties

RewardRateEnabled=false
RewardRateCron=0 0/10 * * * ?
RewardRateDay=1,7,30
MobilitySplit=0.01
RecursionCount=5000

YesterdaysDataEnabled=false
YesterdaysDataCron=0 1 12 * * ?
ConvertCurrency=USDT
RakeBackToChainEnabled=true
RakeBackConvert=USDC

SolanaLpAprEnabled=false
SolanaLpAprCron=0 0 0,6,12,18 * * ?
SolanaLpAprHourlyInterval=1

LPIntervalEnabled=false
LPIntervalCron=0 0/10 * * * ?
LPIntervalMultiple=1.5,2.5
LPInterval=0.01

JtoIntegralEnabled=false
JtoIntegralCron=0 0 0/1 * * ?
JtoStartDate=2024-03-28 24:00:00
JtoEndDate=2027-03-28 24:00:00
JtoAmount=10000

PointsHourEnabled=false
PointsHourCron=0 0 0/1 * * ? 

PointsDayEnabled=true
PointsDayCron=0 14 21 * * ?

