#MDT-Guohai.Shan
#"@include#"---Into the configuration file, eg:"@include#=./control/dbconfig.ini"
#@include#=./control/ServersConfig.ini

####################DBPool Cinfig###############[Begin]###
[DBPOOL]
#DBPool Config
DBPOOL.DBCount=0
DBPOOL.LogLevel=0
DBPOOL.LogPath=./log/DBPool.log

DBPOOL.DBSourceName_0=MYSQL0
DBPOOL.DBDriver_0=com.mysql.cj.jdbc.Driver
#DBPOOL.DBUrl_0=jdbc:mysql://54.251.198.193:3306/dc?charset=UTF-8&parseTime=True&loc=Local
DBPOOL.DBUrl_0=jdbc:mysql://52.77.61.147:3306/dc?charset=UTF-8&parseTime=True&loc=Local
DBPOOL.DBUsername_0=dc
DBPOOL.DBPasswd_0=Kabdnrj@90Ya
DBPOOL.DBCheckSql_0=select 1 from dual
DBPOOL.DBIsEncrypt_0=false
DBPOOL.DBMaxCount_0=10
DBPOOL.DBMinCount_0=5
DBPOOL.DBConnOutTime_0=1000
# 1 minutes the number of detection
DBPOOL.DBConnCheckNumber_0=1000
# After the connection with the treatment strategy,false=waiting,true=get a connection, but DBPool don't manager.
DBPOOL.DBStrategy_0=false

CLICKHOUSE.DBCount=1
CLICKHOUSE.DBSourceName_0=ClickHouse1
CLICKHOUSE.DBUrl_0=jdbc:clickhouse://14.0.47.20:8123/dc?compression=true
CLICKHOUSE.DBUsername_0=default
CLICKHOUSE.DBPasswd_0=123456
CLICKHOUSE.DBIsEncrypt_0=false
CLICKHOUSE.DBMaxCount_0=50
CLICKHOUSE.DBMinCount_0=5
CLICKHOUSE.DBConnOutTime_0=1000
CLICKHOUSE.DBAsyncInsert_0=1
CLICKHOUSE.DBAsyncInsertMaxInternet_0=2000
