##############################################################
# REGISTER  config list
#..................................................
REGISTER.ServerList=REGISTER.Svr1

REGISTER.Svr1.Name=REGISTER1
REGISTER.Svr1.Host=52.77.61.147:2181


NetType=dps


SERVER.BatchSvr.Name=BatchSvr
SERVER.BatchSvr.Host=127.0.0.1:30032
SERVER.BatchSvr.RegType=2
SERVER.BatchSvr.RegisterEnable=0
SERVER.BatchSvr.LBFactor=1
SERVER.BatchSvr.ServiceName=BatchSvr
SERVER.BatchSvr.RegisterServerList=REGISTER.Svr1

SERVER.TradeSOLSvr.Name=TradeSOLSvr
SERVER.TradeSOLSvr.Host=52.77.61.147:30038
SERVER.TradeSOLSvr.RegType=2
SERVER.TradeSOLSvr.RegisterEnable=0
SERVER.TradeSOLSvr.LBFactor=1
SERVER.TradeSOLSvr.ServiceName=TradeSOLSvr
SERVER.TradeSOLSvr.RegisterServerList=REGISTER.Svr1


SERVER.TradeJLPSvr.Name=TradeJLPSvr
SERVER.TradeJLPSvr.Host=52.77.61.147:30039
SERVER.TradeJLPSvr.RegType=2
SERVER.TradeJLPSvr.RegisterEnable=0
SERVER.TradeJLPSvr.LBFactor=1
SERVER.TradeJLPSvr.ServiceName=TradeJLPSvr
SERVER.TradeJLPSvr.RegisterServerList=REGISTER.Svr1

SERVER.AdminSvr.Name=AdminSvr
SERVER.AdminSvr.Host=52.77.61.147:30031
SERVER.AdminSvr.RegType=2
SERVER.AdminSvr.RegisterEnable=0
SERVER.AdminSvr.LBFactor=1
SERVER.AdminSvr.ServiceName=AdminSvr
SERVER.AdminSvr.RegisterServerList=REGISTER.Svr1


SERVER.MDSvr.Name=MDSvr
SERVER.MDSvr.Host=52.77.61.147:30028
SERVER.MDSvr.RegType=2
SERVER.MDSvr.RegisterEnable=0
SERVER.MDSvr.LBFactor=1
SERVER.MDSvr.ServiceName=MDSvr
SERVER.MDSvr.RegisterServerList=REGISTER.Svr1


SERVER.APSSvr.Name=APSSvr
SERVER.APSSvr.Host=52.77.61.147:30035
SERVER.APSSvr.RegType=2
SERVER.APSSvr.RegisterEnable=0
SERVER.APSSvr.LBFactor=1
SERVER.APSSvr.ServiceName=APSSvr
SERVER.APSSvr.RegisterServerList=REGISTER.Svr1